### ISSUE TITLE
Using serde for serialization?

### ISSUE THREAD

**Issue by erickt** [justinsheehy/vertree#18]
As best as I can tell, serde serialization with rmp_serde should be identical to the hand written one (that I'm not 100% sure is msgpack compliant). Would there be any interest in switching over? I'd be happy to help out with that.

**Comment by andrewjstone** [comment]
Yes, that would be great. There should also probably be some sort of header containing a hash of the snapshot.

**Comment by erickt** [comment]
This landed in #19. @andrewjstone I didn't try to add the header, but it'd be pretty simple to add this  in `snapshot.rs`.

**Comment by andrewjstone** [comment]
Yeah, I'm not super worried about that right now. Thanks for all the help.
