### ISSUE TITLE
Please enable travis

### ISSUE THREAD

**Issue by erickt** [justinsheehy/vertree#20]
We have a travis file, but the travis builds are not actually enabled. Could someone turn them on to make sure tests are passing? You should be able to do it by going to this [page](https://travis-ci.org/justinsheehy/vertree).

**Comment by justinsheehy** [comment]
I believe that I've now enabled it, and that we should see the effect after the next pushed commit.

**Comment by justinsheehy** [comment]
Now I see the first round of green builds, so I'm closing this.
